# The configuration file for the Data Aware Neural Architecture Search. This file contains parameters that can be changed to modify the search.

# General Parameters
NUM_MODELS = 10
SEED = None

# Joblib Parameters
NUM_CORES_TO_USE = 1

# Search Space Parameters
# Data: Sample rate and preprocessing type
DATA_SEARCH_SPACE = [[48000, 24000, 12000, 6000, 3000, 1500, 750, 375], [
    "spectrogram", "mel-spectrogram", "mfcc"]]
# Model Layer: Amount of filters, filter size, and activation function
MODEL_LAYER_SEARCH_SPACE = [[2, 4, 8, 16, 32, 64, 128], [
    3, 5], ["relu", "sigmoid"]]

# Model Parameters
OPTIMIZER = "adam"
LOSS_FUNCTION = "sparse_categorical_crossentropy"
METRICS = ["accuracy"]
NUM_OUTPUT_CLASSES = 2
WIDTH_OF_DENSE_LAYER = 10

# Dataset Parameters
# Change to your own path
PATH_NORMAL_FILES = "/Users/emjn/Documents/DTU/Datasets/ToyConveyor/case1/NormalSound_IND/"
# Change to your own path
PATH_ANOMALOUS_FILES = "/Users/emjn/Documents/DTU/Datasets/ToyConveyor/case1/AnomalousSound_IND/"
# Change to your own path
PATH_NOISE_FILES = "/Users/emjn/Documents/DTU/Datasets/ToyConveyor/EnvironmentalNoise_CNT/"
CASE_NOISE_FILES = "case1"
NUM_NORMAL_FILES_TO_USE = 900
NUM_ANOMALOUS_FILES_TO_USE = 200
DATASET_CHANNEL_TO_USE = 1
SOUND_GAIN = 1.0
NOISE_GAIN = 1.0

# Audio Preprocessing Parameters
FRAME_SIZE = 2048  # Traditional values
HOP_LENGTH = 512  # Traditional values
NUM_MEL_FILTERS = 80  # Typically between 40 and 128
NUM_MFCCS = 13  # Traditional values

# Controller Parameters
CONTROLLER = "evolution"  # or "random"
INITIALIZATION = "trivial"  # or "random"
MAX_NUM_LAYERS = 5

# Evaluation Parameters
NUM_EPOCHS = 20
BATCH_SIZE = 32
MODEL_SIZE_APPROXIMATE_RANGE = 100000

# Evolutionary Parameters
POPULATION_SIZE = 10
# The ratio of the population to be discarded and regnerated when the population is updated.
POPULATION_UPDATE_RATIO = 0.5
# The ratio of the updated population to be generated by crossover. The rest of the updated population is generated by mutations
CROSSOVER_RATIO = 0.2

# Do not modify these if you do not know what you are doing.
# The normal and anomalous files are both 10 seconds. Noise files are however longer and need to be cut to 10 seconds.
AUDIO_SECONDS_TO_LOAD = 10
