import tensorflow as tf

# Search space parameters
# Amount of filters, filter size and activation function
MODEL_LAYER_SEARCH_SPACE = ([2, 4, 8, 16, 32, 64, 128], [
                            3, 5], ["relu", "sigmoid"])
INPUT_SEARCH_SPACE = ([48000, 24000, 12000, 6000, 3000, 1500, 750, 325], [
                      "spectrogram", "mel-spectrogram", "mfcc"])  # Sample rate and preprocessing type

# Model Parameters
NUM_OUTPUT_CLASSES = 2
LOSS_FUNCTION = tf.keras.losses.SparseCategoricalCrossentropy()
WIDTH_OF_DENSE_LAYER = 10

# Dataset parameters
PATH_TO_NORMAL_FILES = "/Users/emjn/Documents/DTU/Datasets/ToyConveyor/case1/NormalSound_IND/"
PATH_TO_ANOMALOUS_FILES = "/Users/emjn/Documents/DTU/Datasets/ToyConveyor/case1/AnomalousSound_IND/"
NUMBER_OF_NORMAL_FILES_TO_USE = 900
NUMBER_OF_ANOMALOUS_FILES_TO_USE = 200
DATASET_CHANNEL_TO_USE = 1

# Audio preprocessing parameters
FRAME_SIZE = 2048  # Traditional values
HOP_LENGTH = 512  # Traditional values
NUMBER_OF_MEL_FILTER_BANKS = 80  # Typically between 40 and 128
NUMBER_OF_MFCCS = 13  # Traditional values

# Controller parameters
MAX_NUM_LAYERS = 5

# Evaluation parameters
OPTIMIZER = tf.keras.optimizers.Adam()
NUM_EPOCHS = 10
BATCH_SIZE = 32

# Evolutionary parameters
POPULATION_SIZE = 100
# The ratio of the population to be discarded and regnerated when the population is updated. Not used for Tournament Selection. See tournament size instead.
# POPULATION_UPDATE_RATIO = 0.5
# The ratio of the updated population to be generated by crossover. The rest of the updated population is generated by mutations
CROSSOVER_RATIO = 0.5
TOURNAMENT_SIZE = 5
